---
openapi: 3.0.0
info:
  title: AR.IO Observer
  version: 0.0.1
  description: |
    AR.IO Observer
components:
  schemas:
    ArweaveAddress:
      type: string
    ArweaveId:
      type: string
    Timestamp:
      type: integer
    Evaluation:
      type: boolean
    HealthCheck:
     type: object
     properties:
       uptime: { type: number }
       date: { 
        type: string,
        format: date
       }
       message: { type: string }
    ArnsAssessment:
      type: object
      properties:
        assessedAt: { '$ref': '#/components/schemas/Timestamp'}
        resolvedId: { '$ref': '#/components/schemas/ArweaveId' }
        pass: { '$ref': '#/components/schemas/Evaluation' }
      required:
        - assessedAt
        - resolvedId
        - pass
    GatewayArnsAssessment:
      type: object
      properties:
        prescribedNames:
          type: object
          additionalProperties: { '$ref': '#/components/schemas/ArnsAssessment' }
        chosenNames:
          type: object
          additionalProperties: { '$ref': '#/components/schemas/ArnsAssessment' }
      required:
        - prescribedNames
        - chosenNames
    GatewayArnsAssessments:
      type: object
      additionalProperties: { '$ref': '#/components/schemas/GatewayArnsAssessment' }
    Report:
      type: object
      properties:
        observerAddress: { '$ref': '#/components/schemas/ArweaveAddress' }
        generatedAt: { '$ref': '#/components/schemas/Timestamp' } 
        arnsAssessments: { '$ref': '#/components/schemas/GatewayArnsAssessments' }
      required:
        - observerAddress
        - generatedAt
        - arnsAssessments

paths:
  '/healthcheck':
    get:
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/HealthCheck'
  '/reports/current':
    get:
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/Report'
