name: deploy-observer-image

on:
  workflow_dispatch:
    inputs:
      image_sha:
        description: 'Container image SHA'
        required: true

jobs:
  ar-io-observer-deployment:
    runs-on: ubuntu-latest
    environment: infra

    permissions:
      actions: write
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_BUILD_INVOCATION_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Trigger ar-io-observer deployment
        run: |
          aws lambda invoke \
            --function-name ario-dev-deployment-trigger \
            --region ${{ vars.AWS_REGION }} \
            --cli-binary-format raw-in-base64-out \
            --payload '{"image_sha": "${{ github.event.inputs.image_sha }}", "event_type": "deploy-ar-io-dev-observer"}' \
            /dev/null
